version: "3.9"

services:
  fastapi-server:
    build: .
    container_name: fastapi-server
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://host.docker.internal:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
